- linux-x86/Dockerfile
- linux-x86/Toolchain.cmake
- linux-x86/i686-linux-gnu-as.sh
- test/run.py
This update allows to cross-compile CMake'ified python.
> Add linux x86 toolchain file

- common.docker
Download the CMake binary from CMake.org for SSL support. #39
> manylinux-x64,base: Download cmake binary for SSL support

- manylinux-x64/install-skbuild.sh
- manylinux-x86/install-skbuild.sh
> manylinux-x{64,86}: Bump scikit-build to 0.4.0

- Makefile
- common.manylinux
- manylinux-x64/Dockerfile.in
- manylinux-x86/Dockerfile.in
> No tty sudo

- Dockerfile.in
For improved reliability and performance
> base: Use Debian package repository CDN

- imagefiles/dockcross
> dockcross: Do not leave dangling container on update-script

- common.debian
Setting debian_frontend temporaly to noninteractive
https://github.com/docker/docker/issues/4032
> Debian Frontend

- common.debian
Required for some android builds on @radare... alternatively, how can one easily install new packages in a dockcross container? (su -c/sudo require password).
> Add common (un)archiver, pax

- README.rst
- common.debian
- common.docker
There is a case to be made, that conan's conan.conf could be prepopulated with settings for the compilers. This would have to be made in each of the flavours.
> Added conan support

- manylinux-common/install-python-packages.sh
See http://scikit-build.readthedocs.io/en/latest/changes.html#scikit-build-0-5-1
> manylinux: Update scikit-build to 0.5.1

- common.debian
- common.manylinux
This is crucial/handy for our release engineering (zipping the dist/built objects)... I know unzip is already present but we need to zip, i.e our windows-x86 build.
@radare
> Adding zip

- browser-asmjs/Dockerfile.in
Relates to https://github.com/radare/radare2/pull/6613.
> Bump up emscripten docker container so that it supports WebAssembly

- linux-armv5/Dockerfile
> linux-armv5: Fix cpp path

- linux-armv7/Dockerfile
> linux-armv7: Fix cpp path

- .circleci-matrix.yml
> Update .circleci-matrix.yml to include "linux-mipsel"

- common.debian
- common.docker
- common.manylinux
- imagefiles/entrypoint.sh
- imagefiles/sudo.sh
From:
https://github.com/tianon/gosu
> common: Use gosu to replace chpst and add sudo abilities

- imagefiles/etc/CentOS-Vault.repo
- imagefiles/etc/libselinux.repo
This commit includes files omitted in commit 6e59959 (manylinux: Use
CentOS Vault repositories)
Reported-by: Constantine Grantcharov <cgrantcharov@trustpointinnovation.com>
> manylinux: Add missing repo files

- manylinux-common/install-python-packages.sh
See http://scikit-build.readthedocs.io/en/latest/changes.html#scikit-build-0-6-1
> manylinux: Update scikit-build from 0.5.1 to 0.6.1

- .circleci/config.yml
> circleci: Use anchors and aliases for build settings

- linux-arm64/Dockerfile
> linux-arm64: Fix CPP path

- README.rst
Time it took me to write the instructions: 5 minutes.
Time it took me to figure out how to do the proper forking: 10 minutes.
Time it took me to fix the rotten Markdown: an hour.
> Updated readme to include instructions on extending images.

- LICENSE
> Update LICENSE copyright dates and add @jcfr

- README.rst
> README: Explain difference between dockcross and dockbuild

- imagefiles/entrypoint.sh
xref https://github.com/dockbuild/dockbuild/issues/30
> entrypoint.sh: Update help text so that current image name is used

- README.rst
Suggested-by: Matthew Boehm <github@matthewboehm.com>
Fixes #211
[ci skip]
> README: Fix Articles link

- android-arm/Dockerfile
- android-arm/Toolchain.cmake
Hey, sorry for the two pull requests, I'm not sure what's the best practice for pull requesting when you want to add two features in the same file. I made two pull requests just in case one gets rejected.
Anyway, this pull request features both clang use and added an API variable.
See https://github.com/android-ndk/ndk/issues/648 and https://github.com/dockcross/dockcross/pull/199
> Android - Use clang and add an API variable

- .circleci/config.yml
- Makefile
- README.rst
- android-arm64/Dockerfile
- android-arm64/Toolchain.cmake
Added Android for arm64. How do I add tests for this?
> Add Android-arm64

- .circleci/config.yml
This is a follow-up to 57bf16fa178cec8bd6f20a2bcd505d27fb8892ba
> crossbuild-essential images: disable deploy

- README.rst
New users should see the most relevant sections first. In particular,
- Examples
- Installation
- Usage
> README: Improve section order

- common.windows
Suggested-by: Commaster <Commaster@users.noreply.github.com>
See #181
> common.windows: Optimize image size removing MXE sources

- imagefiles/dockcross
My ws.conf is missing for some reason, which exposed a bug in this script.
> Fixed trying to read wsl.conf when it's missing

- .circleci/config.yml
- common.manylinux
These were disabled -- see #209 #201
> linux-armv5,linux-armv7: Reenable deployment

- common.windows
> windows: Bump MXE to 2018-02-27 master

- README.rst
- manylinux-x64/Dockerfile.in
- manylinux-x86/Dockerfile.in
See https://github.com/pypa/manylinux/pull/273
> manylinux: Trigger rebuild using updated manylinux images having Python 3.8

- Makefile
- linux-armv7a/Dockerfile.in
- linux-armv7a/README.rst
- linux-armv7a/Toolchain.cmake
- linux-armv7a/crosstool-ng.config
PR for https://github.com/dockcross/dockcross/issues/290 .  Feel you free to close the ticket when ready.
Tested with cmake "hello-word" on PocketBeagle board.
I forgot to add link to armv7a image in root README, please add it on your side.
I didn't check CI test just because I do not know how to ) What to read on the subject BTW, I mean info about CI usage in docker context, can I run CI tests on my side? Why CI tests are marked as failing?
> added image for ARMv7-A

- .circleci/config.yml
- README.rst
> Armv7a readme

- imagefiles/dockcross
Fixes https://github.com/dockcross/dockcross/issues/311
> Add missing space in shell if [ ... ]

- common.windows
The one with the last LTS Qt version supported by MXE
> Bump MXE version 1

- imagefiles/build-and-install-cmake.sh
- imagefiles/build-and-install-openssl.sh
The old one was a mirror, and has been taken offline recently.
> Updating CMake repository location

- common.docker
See https://cmake.org/cmake/help/v3.17/release/3.17.html#cmake-3-17-release-notes
> base: Update CMake from 3.16.5 to 3.17.0

- common.docker
See https://cmake.org/cmake/help/v3.17/release/3.17.html#id1
> base: Update CMake from 3.17.0 to 3.17.1

- common.debian
> Kernel initrd build support

- imagefiles/build-and-install-git.sh
Closes issue #395.
Signed-off-by: Mark Van de Vyver <1335713+taqtiqa-admin@users.noreply.github.com>
> Tar extract files as yourself

- common.debian
- web-wasm/Dockerfile.in
> debian: Add libncurses5 for ccmake

- imagefiles/entrypoint.sh
so set-up sudo before .dockcross executes!
> allow .dockcross to use sudo

- linux-x64/Dockerfile
related to https://github.com/dockcross/dockcross/issues/383
> linux-x64: install libelf-dev + libssl-dev

- .circleci/config.yml
> circleci: Deploy manylinux2010-x86

- manylinux2014-x86/Dockerfile.in
Bringing together PR #424 #425
> manylinux2014-x86: Add common.dockcross include

- .github/workflows/main.yml
I used a wrong check in the deploy step conditional (difficult to test without actually trying it :see_no_evil:). This should work better.
> Fix deploy step in CI

- .github/workflows/main.yml
> Deploy base image

- imagefiles/install-python-packages.sh
> base: Update get-pip.py URL

- common-manylinux.crosstool
- common.crosstool
- imagefiles/build-and-install-curl.sh
- imagefiles/crosstool-ng-expat.patch
- imagefiles/install-crosstool-ng-toolchain.sh
changelog: https://curl.se/changes.html#7_76_0
Build on top of #483
Pre-requisite to #481
> chore: update curl 7.52.1 → 7.76.0

- common-manylinux.crosstool
- common.crosstool
- imagefiles/build-and-install-curl.sh
- imagefiles/build-and-install-openssh.sh
- imagefiles/build-and-install-openssl.sh
- imagefiles/crosstool-ng-expat.patch
- imagefiles/install-crosstool-ng-toolchain.sh
changelog: https://www.openssl.org/news/changelog.html#openssl-111
Build on top of #483 / #482 
Fix #380
> chore: update OpenSSL 1.0.2 → 1.1.1k

- imagefiles/build-and-install-openssh.sh
changelog: https://www.openssh.com/releasenotes.html#8.5p1
> chore: update OpenSSH 7.9p1 → 8.5p1

- common.docker
changelog: https://github.com/git/git/blob/master/Documentation/RelNotes/2.31.1.txt
> chore: update git 2.22.0 → 2.31.1

- imagefiles/build-and-install-ninja.sh
changelog: https://github.com/ninja-build/ninja/compare/v1.7.2...v1.10.2
> chore: update Ninja 1.7.2 → 1.10.2

- imagefiles/install-gosu-binary.sh
changelog: https://github.com/tianon/gosu/compare/1.10...1.12
> chore: update gosu 1.10 → 1.12

- README.rst
- imagefiles/dockcross
---
See #382 which seems to have been closed without code.
> dockcross: support using podman

- common.crosstool
- linux-armv7a/Dockerfile.in
- linux-armv7a/crosstool-ng.config
GCC 11
Linux 5.12.12
GLIBC 2.33
Binutils 2.36
> Update linux-armv7a to latest crosstool-ng version

- Makefile
- common.crosstool
- linux-arm64/Dockerfile.in
- linux-arm64/crosstool-ng.config
GCC 11
Linux 5.12.12
GLIBC 2.33
Binutils 2.36
> Update linux-arm64 to latest crosstool-ng version

- common.crosstool
- linux-armv7/Dockerfile.in
- linux-armv7/crosstool-ng.config
GCC 11
Linux 5.12.12
GLIBC 2.33
Binutils 2.36
> Update linux-armv7 to latest crosstool-ng version

- common.crosstool
- linux-armv5/Dockerfile.in
- linux-armv5/crosstool-ng.config
GCC 11
Linux 5.12.12
GLIBC 2.33
Binutils 2.36
> Update linux-armv5 to latest crosstool-ng version

- common.crosstool
- linux-armv5-musl/Dockerfile.in
- linux-armv5-musl/crosstool-ng.config
GCC 11
Linux 5.12.12
GLIBC 2.33
Binutils 2.36
> Update linux-armv5-musl to latest crosstool-ng version

- Dockerfile.in
- common.debian
- linux-x64-clang/Dockerfile.in
Update images to debian bullseye
> Update images to debian bullseye

- .github/workflows/expired.yml
- common/common.windows
- linux-arm64/Dockerfile.in
- linux-armv5-musl/Dockerfile.in
- linux-armv5/Dockerfile.in
- linux-armv6/Dockerfile.in
- linux-armv7/Dockerfile.in
- linux-armv7a/Dockerfile.in
- linux-m68k-uclibc/Dockerfile.in
- linux-mips/Dockerfile.in
- linux-ppc64le/Dockerfile.in
- linux-riscv32/Dockerfile.in
- linux-riscv64/Dockerfile.in
- linux-s390x/Dockerfile.in
- linux-s390x/crosstool-ng.config
- Update Crosstool-ng to latest commit
- Update Windows image: MXE to latest commit (2020-12 to 2021-07)
- Update s390x image to latest version of crosstool-ng
- Fix wrong day count
> Update MXE and crosstool-ng to latest commit and s390x

- imagefiles/entrypoint.sh
- linux-x64-clang/Dockerfile.in
Fix wrong file name in entrypoint dockcross -> dockcross.sh
> Fix wrong file name in entrypoint dockcross -> dockcross.sh

- common/common.windows
- linux-arm64/Dockerfile.in
- linux-armv5-musl/Dockerfile.in
- linux-armv5/Dockerfile.in
- linux-armv6/Dockerfile.in
- linux-armv7/Dockerfile.in
- linux-armv7a/Dockerfile.in
- linux-m68k-uclibc/Dockerfile.in
- linux-mips/Dockerfile.in
- linux-ppc64le/Dockerfile.in
- linux-riscv32/Dockerfile.in
- linux-riscv64/Dockerfile.in
- linux-s390x/Dockerfile.in
- web-wasm/Dockerfile.in
Update crosstool-ng, mxe and wasm
> Update crosstool-ng, mxe and wasm

- imagefiles/build-and-install-curl.sh
- imagefiles/build-and-install-git.sh
- imagefiles/build-and-install-ninja.sh
- imagefiles/build-and-install-openssh.sh
- imagefiles/build-and-install-openssl.sh
- imagefiles/install-cmake-binary.sh
- imagefiles/install-gosu-binary.sh
Improve curl with retry on error
> Improve curl with retry on error

- README.md
> Add linux-armv6-lts in Readme

- common/common-manylinux.crosstool
- common/common.manylinux
- imagefiles/build-and-install-cmake.sh
- manylinux2014-x64/Dockerfile.in
- manylinux2014-x64/Toolchain.cmake
- manylinux2014-x86/Dockerfile.in
- manylinux2014-x86/Toolchain.cmake
Fix manylinux and update to devtoolset-10 : #544
> Fix manylinux2014 and update to devtoolset-10

- common/common.docker
> Update CMake to 3.21.1

- README.md
- Add summary
- Add new badges (Shellcheck CI ect...)
- Remove old badges from microbadger (Not working since july)
- Fix typo
> Improve readme and add summary

- .github/workflows/main.yml
- .github/workflows/shellcheck.yml
- README.md
Update Readme and fix CI
- Add legacy images table
- Fix broken link
- Ignore path in CI: **.md
- Improve image table
> Update Readme and fix CI

- Makefile
- README.md
> Update Readme and Makefile

- android-arm/Dockerfile.in
- android-arm64/Dockerfile.in
- android-x86/Dockerfile
- android-x86_64/Dockerfile
Update android NDK to r23 (August 2021)
> Update android NDK to r23 (August 2021)

- web-wasm/Dockerfile.in
Update emscripten/emsdk to 2.0.27
> Update emscripten/emsdk to 2.0.27

- .github/workflows/main.yml
- Makefile
- README.md
- common/common-manylinux.crosstool
- manylinux2014-aarch64/Dockerfile.in
- manylinux2014-aarch64/Toolchain.cmake
- manylinux2014-aarch64/crosstool-ng.config
- manylinux2014-aarch64/xc_script/docker_setup_scrpits/copy_libstd.sh
- manylinux2014-aarch64/xc_script/docker_setup_scrpits/prepare_cross_env.sh
- manylinux2014-aarch64/xc_script/install_deps.sh
- manylinux2014-aarch64/xc_script/repair_wheel.sh
1) Updated GCC version(9.3) as per manylinux containers and re-pushed manylinux2014-aarch64
2) Added few scripts to support cross-compilation of the wheels
3) Added cross compiled python which is used to cross compile a wheel via [crossenv](https://github.com/benfogle/crossenv)
> Add manylinux2014-aarch64 with gcc=9.3

- .github/workflows/main.yml
I would add new tests in the following PRs, to avoid these issues: #568 
I have changed the lists in the CI a bit, to make it easier after.
The programs to build in CI, to test the images (In the following PRs):
- OpenSSL : https://github.com/openssl/openssl
- Stockfish : https://github.com/official-stockfish/Stockfish
- ninja-build : https://github.com/ninja-build/ninja
And maybe others.
> Update CI: Updating image lists

- web-wasm/Dockerfile.in
> Update emscripten to 2.0.29

- imagefiles/build-and-install-openssl.sh
> Update openssl to 1.1.1i

- imagefiles/build-and-install-openssh.sh
> Update openSSH to V_8_7_P1

- linux-armv6-lts/Dockerfile.in
- linux-armv6-lts/crosstool-ng.config
Update linux-armv6-lts and down GCC version to 8.5.0 #577
> Update linux-armv6-lts and down GCC version to 8.5.0

- tools/dockcross-make-builder.sh
Fix bug with dockcross-make-builder.sh
> Update tools scripts

- .github/workflows/main.yml
- linux-arm64-lts/crosstool-ng.config
- linux-arm64/crosstool-ng.config
- linux-armv5-musl/crosstool-ng.config
- linux-armv5/crosstool-ng.config
- linux-armv6-lts/crosstool-ng.config
- linux-armv6/crosstool-ng.config
- linux-armv7/crosstool-ng.config
- linux-armv7a/crosstool-ng.config
- linux-m68k-uclibc/crosstool-ng.config
- linux-mips/crosstool-ng.config
- linux-ppc64le/crosstool-ng.config
- linux-riscv32/crosstool-ng.config
- linux-riscv64/crosstool-ng.config
- linux-s390x/crosstool-ng.config
- linux-xtensa-uclibc/crosstool-ng.config
- manylinux2014-aarch64/crosstool-ng.config
Update mirror for isl packages: http://ftp.slackware.com/pub/slackware/slackware64-current/source/l/isl
Issues : #606
> Update mirror for isl packages

- .gitignore
- README.md
Update build example in readme: #634 
Update gitignore
> Update build example in readme

- web-wasi/Dockerfile.in
- web-wasm/Dockerfile.in
- web-wasi: Update wasi-sdk to 14.0
- web-wasm: Update Emscripten to 3.0.0
> wasi sdk 14

- imagefiles/install-python-packages.sh
Re: https://github.com/pypa/setuptools/issues/2993
> manylinux: Work around get-pip.py download of distutils

- README.md
| Before | After |
|--|--|
| ![image](https://user-images.githubusercontent.com/219043/152658699-de3a098a-b48f-42f0-a312-448c49ea0a1d.png) | ![image](https://user-images.githubusercontent.com/219043/152658733-bbe15bb4-4685-4f09-8c31-53cd114e1540.png) |
> doc: Updating README adding date to list of retired images

- common/common.webassembly
xref: https://github.com/singlestore-labs/python-wasi/issues/3 https://github.com/wasmerio/wasmer/issues/2810
> wasm: Add libxkbcommon0 dependency for wasmer

- .github/workflows/main.yml
- Makefile
- README.md
- linux-mipsel-lts/Dockerfile.in
- linux-mipsel-lts/Toolchain.cmake
- linux-mipsel-lts/crosstool-ng.config
Add **linux-mipsel-lts** image, fix #684  With GCC 8.5.0, Glibc 2.28 ...
> Add linux mipsel lts image

- .github/workflows/main.yml
- Makefile
- README.md
- linux-mips-lts/Dockerfile.in
- linux-mips-lts/Toolchain.cmake
- linux-mips-lts/crosstool-ng.config
Add mips-lts image, fix #680 With GCC 8.5.0, Glibc 2.28 ...
> Add mips-lts image

- LICENSE
I contributed a lot to the project, I would like to know if you agree?
```
Update LICENSE copyright dates and add @bensuperpc
```
> Update LICENSE copyright dates and add @bensuperpc

- .github/workflows/main.yml
Fixed errors that can sometimes occur with the CI and Improve CI
> Fixed errors that can sometimes occur with the CI and Improve CI

- windows-arm64/Dockerfile.in
- windows-armv7/Dockerfile.in
> Update Windows ARM

- web-wasm/Dockerfile.in
Update web-wasm from 3.1.5 to 3.1.10
> Update web-wasm from 3.1.5 to 3.1.10

- web-wasi/Dockerfile.in
> Update web-wasi to 15.0

- .github/workflows/main.yml
> ci: Make cache download optional

- .github/workflows/main.yml
- CONTRIBUTING.md
- Makefile
- linux-armv7a-lts/Dockerfile.in
- linux-armv7a-lts/README.rst
- linux-armv7a-lts/Toolchain.cmake
- linux-armv7a-lts/crosstool-ng.config
See #678 for context. Support to BeagleBone Black that uses glibc 2.28.
> Added LTS version to linux-armv7a, issue #678

- .github/workflows/main.yml
Update CI and add raylib build test (Only web-wasm for now)
> Update CI and add raylib build test

- imagefiles/cmake.sh
> cmake: don't add toolchain file when installing

- linux-arm64-musl/Dockerfile.in
- linux-armv6-musl/Dockerfile.in
- linux-armv7l-musl/Dockerfile.in
Attempt to fix error with ***-musl** images #724 
> Fix error with musl images

- .github/workflows/main.yml
Fixes the architecture arg passed to openssl when building in the pipeline
> Fix openssl arch type

- common/common.manylinux_2_28
- manylinux2014-x64/Dockerfile.in
- manylinux2014-x86/Dockerfile.in
- manylinux_2_28-x64/Dockerfile.in
- manylinux_2_28-x64/Toolchain.cmake
> manylinux_2_28-x64: Update for gcc-toolset-12

- imagefiles/wasmer-pwd.sh
- imagefiles/wasmtime-pwd.sh
Ensure there is access to the source tree for try_run's.
> web-wasi: mount /work in emulator for access to working directory

- .github/workflows/main.yml
- Makefile
- README.md
- linux-mips-uclibc/Dockerfile.in
- linux-mips-uclibc/Toolchain.cmake
- linux-mips-uclibc/crosstool-ng.config
Hey,
so we (CC: @LukasEpheser) created a  `linux-mips-uclibc` container to compile some code for MIPS-based linux routers.
As it is a quite common combination, we thought that it might be worth to contribute.
Cheers
> add linux-mips-uclibc container

- .github/workflows/main.yml
- Makefile
- README.md
- linux-ppc64le-lts/Dockerfile.in
- linux-ppc64le-lts/Toolchain.cmake
- linux-ppc64le-lts/crosstool-ng.config
Add image **linux-ppc64le-lts** image: https://github.com/dockcross/dockcross/issues/782
GCC 8.5 and Glib 2.28 tested on Debian 10 (buster) with QEMU
> Add linux-ppc64le-lts image

- .github/workflows/main.yml
- .gitignore
- Dockerfile.in
- android-arm64/Dockerfile.in
- common/common.windows
- imagefiles/install-python-packages.sh
- linux-x64-clang/Dockerfile.in
- web-wasi/Dockerfile.in
> Update to debian bookworm

- web-wasm/Dockerfile.in
> web-wasm: bump emscripten to 3.1.60

- common/common.label-and-env
- common/common.webassembly
- web-wasi-threads/Toolchain.cmake
- web-wasi/Dockerfile.in
- web-wasi/Toolchain.cmake
- web-wasi/clang++-wasi-sysroot.sh
- web-wasi/clang-wasi-sysroot.sh
- web-wasi/download-install-wasi-sdk.sh
- web-wasi: bump to wasi-sdk 25.0
- common: bump binaryen, wabt to latest
> wasi sdk 25

- web-wasi-threads/Dockerfile.in
- web-wasi-threads/Toolchain.cmake
- web-wasi-threads/clang++-wasi-threads-sysroot.sh
- web-wasi-threads/clang-wasi-threads-sysroot.sh
> web-wasi-threads: use target wasm32-wasi-threads in sysroot wrapper

- imagefiles/entrypoint.sh
https://github.com/dockcross/dockcross/issues/890
> fix /dev/pts/0 permissions

- .github/workflows/main.yml
- android-arm/Dockerfile.in
- android-arm64/Dockerfile.in
- android-x86/Dockerfile
- android-x86_64/Dockerfile
Support Android 16KB.
https://developer.android.google.cn/guide/practices/page-sizes#compile-r28
> Update ndk to r28b
