README.rst
linux-ppc64le/Dockerfile
linux-ppc64le/Toolchain.cmake

This commit updates the toolchain to ensure libraries associated with
ppc64le can be found.
Since the libraries are all installed on the system and not in dedicated
root, `FIND_ROOT_PATH` should *not* be specified.

linux-ppc64le: Specify system processor and fix library finding.

---

linux-armv5/Dockerfile

Just followed the official debian cross-compiling guide for Jessie with a couple of tweaks:
https://wiki.debian.org/CrossToolchains#For_jessie_.28Debian_8.29

Fixed armel (armv5) jessie docker build

---

.gitignore
Makefile
circle.yml

In addition to the existing targets:
```
make android-arm
make browser-asmjs
...
```
there are now 
```
make android-arm.test
make browser-asmjs.test
...
```
and also 
```
make tests
```

Fix circle error and tweak makefile

---

imagefiles/entrypoint.sh
manylinux-x64/Dockerfile.in

This will allow build script like "build-wheels.sh" to run command like
the following (see [1]):
```
sudo yum install -y atlas-devel
```
It will also allow to pip install using sudo and avoid error reported in [3].
That said, instead of running pip using sudo, the recommended approach
is to specify the "--user" flag [2]
[1] https://github.com/pypa/python-manylinux-demo/blob/893d92517e9e289b9d2ee063f19c3216a39534ab/travis/build-wheels.sh
[2] http://stackoverflow.com/questions/7143077/how-can-i-install-packages-in-my-home-folder-with-pip#7143496
[3] Error reported when running pip without "sudo pip install <packagename" or "pip install --user <packagename>"
```
Exception:
Traceback (most recent call last):
File "/opt/_internal/cpython-2.7.11-ucs2/lib/python2.7/site-packages/pip/basecommand.p …
```

manylinux: Grant current user password less sudo access.

---

Makefile
README.rst
circle.yml

This topic improves and simplifies the `Makefile`:
* Add documentation
* Define image as either `standard` or `non-standard`
* Create  `ALL_IMAGES` and `DEFAULT_IMAGES` categories
* Make use of implicit build and testing rules if relevant
* Add convenience targets `display_all_images` and `display_default_images`, and also document how to easily download all images and/or install all dockcross scripts into `~/bin`.
To make sure that no regression were introduced, the output of `make --dry-run` was compared before and after each commit. See below for more details.
To confirm that the Makefiles works as expected after this patch, the
list of executed commands before and after is compared:
Before:
browser-asmjs linux-ppc64le
```
make --dry-run > ../dockcross-make-baseline
make test --dry-run …
```

Tweak makefile

---

imagefiles/dockcross

This commit workarounds the problem described in [1] and [2] by ignoring error
happening when deleting container in unprivileged LXC container.
Fixes #50
[1] https://circleci.com/docs/docker-btrfs-error/
[2] https://discuss.circleci.com/t/docker-error-removing-intermediate-container/70

dockcross: Ignore deletion error when running in unprivileged LXC container

---

imagefiles/dockcross

As explained in [1], when using dockcross from python subprocess, the
interactive mode is disabled and output of `cat /dev/urandom` is _block
buffered_ instead of being _line buffered_.
Workaround to this problem is to simply read a fixed amount of characters
from urandom.
The following two snippets illustrates the problem and the
the implemented  solution:
Works
``` python
import subprocess as sp
sp.check_call("var=$(head -c 500 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | fold -w 7 | head -n 1); echo $var", shell=True)
```
=> output random string
Fail:
``` python
import subprocess as sp
sp.check_call("var=$(cat /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | fold -w 7 | head -n 1); echo $var", shell=True)
```
=> Hang
[1] http://stackoverflow.com/questions/16805827/unable-to-read-stdout-from …

dockcross: Prevent dockcross from blocking when used with Python subprocess

---

Dockerfile.in
Makefile
android-arm/Dockerfile
browser-asmjs/Dockerfile
linux-arm64/Dockerfile
linux-armv5/Dockerfile
linux-armv6/Dockerfile
linux-armv7/Dockerfile
linux-ppc64le/Dockerfile
linux-x64/Dockerfile
linux-x86/Dockerfile
manylinux-x64/Dockerfile.in
manylinux-x86/Dockerfile.in
windows-x64/Dockerfile
windows-x86/Dockerfile

This commit build each images with the following arguments:
- IMAGE: Name of the image (e.g dockcross/base, dockcross/manylinux-x64, ...)
- VCS_REF: dockcross/dockcross commit from which this image is built
- VCS_URL: this repository obtained reading remote.origin.url
- BUILD_DATE: Date and time when the build was initiated
Then, within the Dockerfile, the metadata are associated with the image
using the "LABEL" instruction.
See https://docs.docker.com/engine/reference/builder/#/label
The corresponding labels can be found here:
http://label-schema.org/rc1/#build-time-labels
See #28

dockerfile: Keep track of buildtime metadata

---

common.docker

Improves cross-compilation support in add_custom_command by integrating
https://gitlab.kitware.com/cmake/cmake/merge_requests/217
CMake Git master from 2016-11-03 (3.8-master).
Addresses #54

base: Bump CMake for improved add_custom_command

---

common.manylinux
imagefiles/entrypoint.sh
manylinux-common/pre_exec.sh

While the use of sudo (made possible by 53cf084) allows to install
additional packages, the warning copied below was still reported.
To avoid this warning and streamline the installation of new packages,
this commit (1) introduces the concept of "pre_exec" entrypoint hook
and (2) adds such a hook to change the ownership of python "bin" and
"site-packages" directories for the manylinux images.
Warning reported are similar to this one:
```
The directory '/home/jcfr/.cache/pip/http' or its parent directory is
not owned by the current user and the cache has been disabled. Please
check the permissions and owner of that directory. If executing pip
with sudo, you may want sudo's -H flag.
```
Note that the sudo "-H" flag suggested in the warning is not available
in centos.

manylinux.common: Fix warning changing ownership of python install

---

common.docker

If images are any of manylinux-x86, manylinux-x64, linux-x86 or linux-x64,
OpenSSL libraries are installed in /usr .

common.docker: Ensure openssl-1.0.2j is available in manylinux and linux images

---

linux-x64/Toolchain.cmake
manylinux-x64/Toolchain.cmake
manylinux-x86/Toolchain.cmake

Similarly to the linux-x86 toolchain, gcc is used to compile assembler
file.

[many]linux-(x86|x64)/: toolchain: Fix ASM compiler

---

common.docker

This commit fixes the following error reported when building the base
image.
```
sh: 1: [: =: unexpected operator
sh: 1: [: =: unexpected operator
```
It turns out that (1) DEFAULT_DOCKCROSS_IMAGE is not set when building the
base image and (2) latest openssl will not be available in linux-x64 and
linux-x86 images.

base: Fix building of OpenSSL. See #73

---

.gitignore
Dockerfile.in
Makefile
common.docker
imagefiles/install-cmake.sh
imagefiles/install-openssl.sh
linux-x86/Dockerfile

To accommodate the requirements associated with x86 and x64 images, the
command building OpenSSL and CMake became overly complex and hard to
maintain.
This commit has multiple purposes:
(1) simplify common.docker
(2) fix the building of 64-bit shared libraries against the static openssl
libraries by passing the -fPIC flag.
(3) ensure [many]linux-x86 and [many]linux-x64 images have an up-to-date
OpenSSL install. Openssl static libraries are installed in /usr
(4) simplify and speedup CMake build avoiding the second build with
explicit -DCMAKE_USE_OPENSSL:BOOL=ON. Indeed, configuring CMake on Linux
already looks for OpenSSL.
(5) speedup download of CMake source directly downloading the archive
corresponding to the revision.
(6) test CMake by:
- running CMake.FileDownload test
- trying to …

common.docker: Improve OpenSSL and CMake install introducing helper scripts

---

Dockerfile.in
Makefile

To avoid dependent images to systematically rebuild, this commit
adds only "static" metatdata to the base image

base: Optimize image build adding only image and vcs_url metatdata

---

Makefile
imagefiles/dockcross

This commit follows up on 2e71db2 (dockcross: Ignore deletion error
when running in unprivileged LXC container) by hiding the message
only when (a) the command output matches the expected error message
and (b) is executed on CircleCI.
Doing so will avoid adding "noise" to log of service like CircleCI
that are effectively running docker in unprivileged LXC container.
See #50

dockcross: Ensure deletion error are ignored

---

Makefile

This commit fixes a regression introduced in 6823cb1 (Makefile: Do not
specify "--rm" docker run argument when executing on CircleCI)

Makefile: Fix tests removing double quote from RM variable

---

common.debian

The ``bc`` utility is required to build the 4.x Linux kernel series as described [here](https://www.kernel.org/doc/Documentation/Changes).
This change installs the ``bc`` package when creating the dockcross base image.
Testing: built all docker images, built latest stable Linux kernel 4.8.11, happyness.

common: add bc package

---

imagefiles/dockcross

This commit will avoid the following error from being reported
on MacOSX:
```
docker run --rm dockcross/linux-armv7 > ./dockcross-linux-armv7
chmod +x ./dockcross-linux-armv7
./dockcross-linux-armv7 bash -c '$CC test/C/hello.c -o hello_arm'
grep: /proc/version: No such file or directory
grep: /proc/version: No such file or directory
```
Reported-by: Chris Warth <cswarth@gmail.com>

dockcross: Check if "/proc/version" exists and fix error on MacOSX. Fixes #94

---

manylinux-common/pre_exec.sh

This commit will fix installation of packages like nose that would otherwise
fail to install with error like the following:
Installing collected packages: nose
Exception:
Traceback (most recent call last):
[...]
Permission denied: '/opt/_internal/cpython-2.7.11-ucs2/man'

manylinux-common: Fix pip install change ownership of "man" and "share" dir

---

linux-mipsel/Dockerfile

linux-mipsel: Fix toolchain environmental variable paths

---

common.debian
common.manylinux
imagefiles/dockcross

Added SSH support to enable Git checkouts that use SSH instead of
HTTP(S).
The SSH directory is assumed to be in $HOME/.ssh; however:
export SSH_DIR=/my/custom/dir
will override the setting and allow for configurable settings.
$SSH_DIR is then mounted as host-volume in the Docker container and
placed in /home/\<user\>/.ssh

SSH Support for Git Clone / Checkout

---

common.manylinux

This requires that sudo supports '-E', which gosu does not.

manylinux: Remove rh devtoolset sudo

---

common.docker

Hi,
Thanks for these useful images.
While I was using dockcross/linux-armv7 image, I've noticed pip is broken like below.  pip is broken just after conan installation.  This happens on all linux-* images since pip is broken at dockcross/base image.  This PR will fix it.  I've tested this modifications by `make base` and `make manylinux-x64`.
```
$ dockcross-linux-armv7 pip
Traceback (most recent call last):
File "/usr/bin/pip", line 9, in <module>
load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
return ep.load()
File …
```

linux-*: Change common.docker to fix pip installation.

---

imagefiles/entrypoint.sh

BUG:
Creating a new directory under /home/\<user\>/ from the /work folder does
not work. In fact, going into the home directory and trying to run mkdir
fails as well.
SOLUTION:
Turns out chown -R \<user\>:\<user\> was run on $HOME/* instead of on $HOME.
This means that /home/\<user\> was still under the ownership of root:root,
hence preventing any writes to non-root users.

Fix $HOME directory ownership permissions

---

Makefile
README.rst
common.crosstool
imagefiles/install-crosstool-ng-toolchain.sh
linux-mips/Dockerfile.in
linux-mips/Toolchain.cmake
linux-mips/crosstool-ng.config

Add a mechanism to construct a full cross-compiler environment using the
"crosstool-ng" cross-compiler building utility. This is implemented in
the new "common.crosstool" include, and augments the "dockcross/base"
base image. See #152 .
Update Makefile to consolidate Dockerfile generation, notably the
"sed"-based inclusion directives.
Finally, employ all of this to generate a "linux-mips" 32-bit hard-float
MIPS cross-compiler Dockcross image.

Implement "ct-ng" building, add "linux-mips".

---

windows-x64/Dockerfile
windows-x86/Dockerfile

MXE now ships its own version of CMake that sources the toolchain file,
etc. As suggested by their warning when sourcing the toolchain file, use
it.
This also results in updating GCC from 4.9 to 5.4.

windows-{x64,x86}: Bump MXE to 2017-10-25 master

---

imagefiles/dockcross

Otherwise `--` is sent as the command...

Missing shift in dockcross -- command [args]

---

imagefiles/install-cmake.sh

I'm trying to build [PyMesh](http://pymesh.readthedocs.io/en/latest/installation.html) on dockcross/manylinux-x64 and to get it done I need a newer version of CMake.
The following issue comes up in the PyMesh build: https://gitlab.kitware.com/cmake/cmake/issues/16509 and the fix was merged in v3.10: https://gitlab.kitware.com/cmake/cmake/merge_requests/1009

bump cmake to v3.10.1

---

browser-asmjs/Dockerfile.in

Addresses:
```
WARNING:root:emcc: cannot find library "rt"
INFO:root:generating system library: dlmalloc_debug.bc... (this will be cached in "/emsdk_portable/.cache/asmjs/dlmalloc_debug.bc" for subsequent builds)
Traceback (most recent call last):
File "/emsdk_portable/sdk/em++", line 16, in <module>
emcc.run()
File "/emsdk_portable/sdk/emcc.py", line 1411, in run
extra_files_to_link += system_libs.calculate([f for _, f in sorted(temp_files)] + extra_files_to_link, in_temp, stdout_=None, stderr_=None, forced=forced_stdlibs)
File "/emsdk_portable/sdk/tools/system_libs.py", line 485, in calculate
libfile = shared.Cache.get(name, do_create, extension=suffix)
File "/emsdk_portable/sdk/tools/cache.py", line 102, in get
shutil.copyfile(temp, cachename)
File "/usr/lib/python2.7/shutil.py", line …
```

browser-asmjs: Bump Emscripten version and address cache permissions

---

imagefiles/dockcross

Changed Windows Subsystem for Linux's PWD to be the physical path rather than relative since windows cannot traverse a relative path inside the Linux subsystem.

QuickFix for issue #186

---

browser-asmjs/Dockerfile.in

Hi, I found a simple improvement for your image. 
https://github.com/asRIA/emscripten-docker/pull/16 creates $EM_DATA with cache and 777 permissions
**Context**
* Paths to folders: https://github.com/asRIA/emscripten-docker/blob/79343484f38dfbdea85235e752fb7f35c633f871/docker/trzeci/emscripten-slim/Dockerfile#L13-L16
* Change permission: https://github.com/asRIA/emscripten-docker/blob/79343484f38dfbdea85235e752fb7f35c633f871/docker/trzeci/emscripten-slim/Dockerfile#L183
------
BTW: If I may ask: Was it somehow required for you to put Emscripten folders to the `PATH`?

Remove duplicated code from base image.

---

imagefiles/entrypoint.sh

This commit is a follow up of b7028af (entrypoint.sh: Update help
text so that current image name is used)
It ensures that the suggested script in the help text doesn't include ":"
in its name.
Assuming DEFAULT_DOCKCROSS_IMAGE is set to "dockcross/imagename:latest"
Instead of suggesting:
```console
[...]
[...]
```
it will now suggest
```console
[...]
[...]
```
xref https://github.com/dockbuild/dockbuild/issues/30
[ci skip]

entrypoint.sh: Account for image tag when updating help text

---

.circleci/config.yml

Temporarily disable because the packages are not available. See #209.
These should be replaced by crosstool-ng images.

crossbuild-essential images: disable because of missing packages

---

imagefiles/dockcross

From https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly#ensure-volume-mounts-work
>When using WSL, Docker for Windows expects you to supply your volume paths in a format that matches this: /c/Users/nick/dev/myapp.
>Create and modify the new WSL configuration file:
>sudo nano /etc/wsl.conf
>
>Now make it look like this and save the file when you're done:
>[automount]
>root = /
>options = "metadata"

Wsl better support

---

.circleci/config.yml
Makefile
README.rst
common.windows
windows-x64-posix/Dockerfile.in
windows-x64/Dockerfile.in
windows-x86/Dockerfile.in

This pull request adds new image windows-x64-posix.
This is based on @jcfr's recent windows refactoring.
To do so, I have added variable `MXE_TARGET_THREAD` that is empty for the classical windows image, and set to `.posix` for posix image. This variable is inserted to access the correct programs while building image and for variable `MXE_TARGETS` used by mxe.
It should address problem reported [here](https://github.com/dockcross/dockcross/issues/216) and discussed with @thewtex  and @jcfr.
I wanted to add a simple test program cpp with `std::thread` inside, but had no clue how to insert 
We could do the same for fortran programs.
Other things:
- it would be nice to link images found on [dockerhub](https://hub.docker.com/r/dockcross) and on GitHub: for example having git sha on dockcross …

Added new image windows-x64-posix

---

README.rst
android-arm64/Dockerfile

The purpose of this commit is to rebuild the dockcross images against
the latest manylinux images including Python 3.7 and also updated
setuptools, autitwheel, git, curl, ...
Note that python 3.3 was removed from the image.
```
$ docker run -ti --rm quay.io/pypa/manylinux1_x86_64 bash -c "ls -1 /opt/python/"
cp27-cp27m
cp27-cp27mu
cp34-cp34m
cp35-cp35m
cp36-cp36m
cp37-cp37m
```

manylinux: Re-build images using latest base images

---

common.windows

Contrary to the comment above this line, deleting the .git directory breaks build of additional packages in derived images.
Example of building bzip2 with the original Dockerfile:
```
fatal: Not a git repository (or any of the parent directories): .git
[pkg-list]  bzip2
-- snip -- (Downloading stuff)
Failed to build package bzip2 for target x86_64-w64-mingw32.static!
------------------------------------------------------------
Linux cd0675946b5d 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 GNU/Linux
git log --pretty=tformat:"%H - %s [%ar] [%d]" -1
fatal: Not a git repository (or any of the parent directories): .git
Makefile:660: recipe for target 'build-only-bzip2_x86_64-w64-mingw32.static' failed
make[1]: *** [build-only-bzip2_x86_64-w64-mingw32.static] Error 128 …
```

do not delete mxe's .git directory

---

.gitattributes

This could cause issues with bash if their are Windows line endings.

git: Ensure we use lf endings

---

README.rst
imagefiles/build-and-install-cmake.sh
imagefiles/build-and-install-curl.sh
imagefiles/build-and-install-git.sh
imagefiles/build-and-install-ninja.sh
imagefiles/build-and-install-openssh.sh
imagefiles/build-and-install-openssl.sh
imagefiles/ccmake.sh
imagefiles/cmake.sh
imagefiles/dockcross
imagefiles/entrypoint.sh
imagefiles/install-cmake-binary.sh
imagefiles/install-crosstool-ng-toolchain.sh
imagefiles/install-gosu-binary.sh
imagefiles/install-liquidprompt-binary.sh
imagefiles/install-python-packages.sh
imagefiles/utils.sh
linux-x86/i686-linux-gnu-as.sh
linux-x86/i686-linux-gnu.sh
manylinux-common/install-python-packages.sh
manylinux-common/pre_exec.sh

`#!/usr/bin/env bash` should be used to avoid hard paths.
To address:
dockcross-manylinux-x64: bad interpreter: /bin/bash^M: no such file or directory

common: Fix bash shell script invocation

---

linux-armv7/crosstool-ng.config

This fixes the cross compiled runtime on a RPi.

Pinned armv7 ABI to use hard float

---

imagefiles/dockcross

If `id -un` or `id -gn` outputs a name containing a space, e.g. when joined to an AD domain with SSSD, the current `dockcross` script would break and abort with an error: `docker: invalid reference format.`, because it would interpret the part after the space as an image name.

Fix dockcross script for users/groups containing spaces

---

.circleci/config.yml
Makefile
android-arm/Dockerfile
android-arm64/Dockerfile
linux-arm64/Dockerfile.in
linux-armv5/Dockerfile.in
linux-armv6/Dockerfile
linux-armv7/Dockerfile.in
linux-mips/Dockerfile.in
linux-mipsel/Dockerfile
linux-ppc64le/Dockerfile
linux-s390x/Dockerfile.in
linux-x64/Dockerfile
linux-x86/Dockerfile
manylinux-x64/Dockerfile.in
manylinux-x86/Dockerfile.in
windows-x64-posix/Dockerfile.in
windows-x64/Dockerfile.in
windows-x86/Dockerfile.in

This ensures that the dockcross script will continue to use the specific
tagged version of the image that generates it.

versioning: Set DEFAULT_DOCKCROSS_IMAGE based on the image tag

---

linux-armv7a/crosstool-ng.config

automake and libtool are missing from the armv7a target (they are enabled in other targets).  This pull request adds them.

updated armv7a to enable libtool and automake

---

imagefiles/build-and-install-openssl.sh

`openssl-1.0.2r` no longer available

bump openssl version to openssl-1.0.2s

---

.circleci/config.yml
Makefile
README.rst
linux-armv5-musl/Dockerfile.in
linux-armv5-musl/Toolchain.cmake
linux-armv5-musl/crosstool-ng.config

This pull request add a toolchain form arm5 using musl as a base libc library. It allows compiling new software (i.e. C++11) on very old kernels. Tested with C++14 features, Boost, and several libraries like alsa sound, libogg, tremor, libao, etc., all in kernel 2.6.28.2.

Add support for arm5-musl

---

README.rst
manylinux1-x64/Toolchain.cmake
manylinux1-x86/Toolchain.cmake
manylinux2010-x64/Toolchain.cmake

So that one can do `if (MANYLINUX1)` in CMake, just like it is commonly done with e.g. `if (IOS)` or `if (MSVC)`.
I believe that it doesn't hurt, and it may be the only way to detect that it is a manylinux build (some projects already pass that information as an argument to the cmake call, which doesn't seem elegant to me).
Resolves #327.

Manylinux toolchain: set MANYLINUX1/MANYLINUX2010 to TRUE

---

manylinux1-x64/Toolchain.cmake
manylinux1-x86/Toolchain.cmake
manylinux2010-x64/Toolchain.cmake

I tried it in a small cmake project: as described in #326, setting `CMAKE_SYSTEM_NAME` will have cmake set `CMAKE_CROSSCOMPILING` to `TRUE`. Which I believe is wrong in the manylinux case. Adding `set(CMAKE_CROSSCOMPILING FALSE)` to the `CMAKE_TOOLCHAIN_FILE` overrides that behavior.
I was not sure exactly how to check that it doesn't break anything in dockcross/manylinux*, so I figured I would open a PR to get feedback.
Resolves #326.

Manylinux toolchains: restore CMAKE_CROSSCOMPILING

---

linux-armv7/Toolchain.cmake

This is necessary if one wants to be able to use libraries or
includes or programs installed locally (and not on the system
of the build machine, or in CMAKE_SYSROOT, or in CMAKE_FIND_ROOT_PATH).
According to cmake order for find_* functions, CMAKE_FIND_ROOT_PATH
will be searched before the system of the build machine anyway,
which doesn't dramatically change the current behavior.
NOTE: This PR is only for linux-armv7 because that is the one I tested, but I believe I will have exactly the same issue on others. My idea was to open new PRs as I test those other systems.
Resolves #334.

Update Toolchain.cmake to use BOTH for CMAKE_FIND_ROOT_PATH_MODES

---

linux-arm64/Dockerfile.in
linux-armv5-musl/Dockerfile.in
linux-armv5/Dockerfile.in
linux-armv6/Dockerfile
linux-armv7/Dockerfile.in
linux-armv7a/Dockerfile.in
linux-mips/Dockerfile.in
linux-mipsel/Dockerfile
linux-ppc64le/Dockerfile
linux-s390x/Dockerfile.in
linux-x86/Dockerfile

Set the ARCH, CROSS_COMPILE and PATH variables to support Linux kernel
cross compilation.
ARCH is set according to:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/arch?h=v5.2.2
PATH is set to include the cross toolchain path, which is used by the
kernel Makefile.
CROSS_COMPILE is the CROSS_TRIPLE with a dash appended, as the kernel
Makefile uses it to invoke the toolchain utils.
To build the kernel, depending on the config, _libssl-dev_ and _libelf-dev_
are required. Those are not dealt in this commit as they are not
correlated to the environment variables.
Validated by build the kernel using default kernel config when possible,
otherwise randomly select a defconfig.
**arch** - **defconfig**
arm64 - defconfig
armv5 and armv5-musl - colibri_pxa270_defconfig
armv6 - …

Set environment variables for Linux kernel cross compilation

---

.circleci/config.yml
Makefile
README.rst
common.docker
common.manylinux
imagefiles/build-and-install-openssl.sh
manylinux2010-x64/Dockerfile.in
manylinux2010-x86/Dockerfile.in
manylinux2010-x86/Toolchain.cmake

Added `dockcross/manylinux2010-x86` as official [manylinux2010-x86](https://quay.io/repository/pypa/manylinux2010_i686) came out.
Updated `dockcross/manylinux2010-x64` to use official upstream base [docker image](https://quay.io/repository/pypa/manylinux2010_x86_64).

Add manylinux2010-x86

---

.circleci/config.yml
Makefile
README.rst
manylinux2014-x64/Dockerfile.in
manylinux2014-x64/Toolchain.cmake

This is bringing manylinux2014-x64 to dockcross.
* I naively copied the Dockerfile and Toolchain from manylinux2010.
* I use `FROM quay.io/pypa/manylinux2014_x86_64`, I don't know if I could/should fix that to a tag somehow.
* I checked all the paths against manylinux2014, and they all seemed valid as far as I could tell.
* I tried to build manylinux2014-x64 locally (`$ make manylinux2014-x64`).
* I tried to run the tests (`$ make manylinux2014-x64.test`), and it seems to me that they did not fail (output below).
* I built my project with my new manylinux2014-x64 image, and it ended up in an executable that runs on my linux machine and that does not link to dependencies I would not expect.
```
% ldd ./build/manylinux2014-x64/src/backend/src/mavsdk_server …
```

add support for manylinux2014-x64

---

common.windows

The default version of gcc for mxe is 5 which is too stale to support C++17. Let's bump the version of gcc to 9 to gain all the benefit that the recent gcc provides such as C++17 support and performance optimization ([changes](https://gcc.gnu.org/gcc-9/changes.html)).

Changed the version of gcc for mxe to 9

---

manylinux2014-x64/Dockerfile.in

This is the only tag kept on quay.io.

manylinux2014_x86_64: Use latest for base image version

---

manylinux2014-x64/Dockerfile.in

This patch is intended to trigger a build / deploy based on the latest
upstream manylinux2014-x64 image.

doc: Note that yum addressed in recent manylinux2014-x64

---

manylinux2014-x64/Dockerfile.in

Based on the manylinux2010 workaround.

manylinux2014-x64: Add yum libcurl workaround

---

common.docker

To be conservative, I only updated to use 3.16.5
That said, version 3.17.0 is also available as a dockerbuild release as well. See https://github.com/dockbuild/CMake/releases

base: Update CMake from 3.13.2 to 3.16.5

---

linux-arm64/crosstool-ng.config

linux-arm64 is currently using gcc 4, so it's difficult to take
advantage of modern C++. This PR bump up the version of gcc to
allow us to enjoy all the benefits of modern C++. (This PR is based
on #310)

[linux-arm64] bump up the version of gcc to 8

---

imagefiles/dockcross

so `docker` mounts the volume properly.
Looks like https://github.com/dockcross/dockcross/issues/186 / https://github.com/dockcross/dockcross/pull/189 addressed the issue for Docker on Windows.
This issue still exists for `MSYS`... Unfortunately, I don't have a Windows machine (right now) to work on a fix...

if PWD is a symbolic link then read / find the link

---

.circleci/config.yml
Makefile
README.rst
common-manylinux.crosstool
imagefiles/install-crosstool-ng-toolchain.sh
imagefiles/install-liquidprompt-binary.sh
manylinux2014-aarch64/Dockerfile.in
manylinux2014-aarch64/Toolchain.cmake
manylinux2014-aarch64/crosstool-ng.config

Resolves #367.
Add support for manylinux2014-aarch64:
- Added Dockerfile, Toolchain, and crosstool config (Referred linux-arm64 wherever requried).
- Using FROM dockcross/manylinux2014-x64 image.
- Updated Makefile.
- To build manylinux2014-aarch64 locally just use 'make manylinux2014-aarch64'.
- Run test is successful. Used 'make manylinux2014-aarch64.test.
- Also added manylinux2014-aarch64 in circleCI config file referring manylinux2014-x64.

Add support for manylinux2014-aarch64

---

manylinux2014-aarch64/Dockerfile.in

This commit overrides variables inherited from the base image.

manylinux2014-aarch64: Set AUDITWHEEL_ARCH and AUDITWHEEL_PLAT variables

---

common-manylinux.crosstool
common.manylinux

This commit removes sudo provided by devtoolset since it doesn't work with
our sudo wrapper calling gosu.
It fixes error like the following:
```
/opt/rh/devtoolset-9/root/usr/bin/sudo: line 41: /usr/bin/sudo: No such file or directory
```
Adapted from e513a26 (manylinux: Remove rh devtoolset sudo)
Co-authored-by: odidev <odidev@puresoftware.com>

manylinux.crosstool: Fix use of sudo removing sudo provided by devtoolset

---

Dockerfile.in
Makefile
common.debian
common.dockcross
common.docker
common.manylinux
manylinux1-x64/Dockerfile.in
manylinux1-x86/Dockerfile.in
manylinux2010-x64/Dockerfile.in
manylinux2010-x86/Dockerfile.in
manylinux2014-x64/Dockerfile.in
web-wasm/Dockerfile.in

Closes #423 
NOTE: This is slightly different than what is mentioned in the issue.
1. This makes an attempt to utilize the "common.dockcross" by the other dockerfiles
2. This does not include apt-get's to install dependencies because they are incompatible with the existing common.debian (and certainly with the manylinux image).

Split "dockcross" script and it's dependencies to separate include

---

imagefiles/install-gosu-binary-wrapper.sh

Make the custom sudo script based on gosu closer to the real sudo by supporting user and group and ignoring unsupported arguments, which is helpful to handle the case of `sudo -p message` frictionlessly.

Better sudo script

---

.circleci/config.yml
Makefile
README.rst
common.docker
common.manylinux
manylinux2014-x86/Dockerfile.in
manylinux2014-x86/Toolchain.cmake

Added `manylinux2014-x86` based on `manylinux` with some modification:
- Skipping installing `epel-release` package only for `manylinux2014-x86` because EPEL stopped supporting x86 from CentOS 7.
- Adding `/opt/rh/devtoolset-9/root/usr/bin/sudo` to a list of files to be removed for gosu.
- Changing the description of `manylinux2014` to have Python 3.5 or later since it stopped supporting Python 2.7 and 3.4.

Added manylinux2014-x86

---

web-wasm/Dockerfile.in

web-wasm: Make emscripten cache writable by non-root

---

Makefile

By deferring the evaluation of `TAG`, we risk the date changing mid-build leading to images from the same `make` invocation having different tags. The date and commit hash from when the build was _started_ are now used throughout.

Eagerly evaluate TAG, to ensure it's consistent

---

.circleci/config.yml
Makefile
README.rst
linux-arm64-musl/Dockerfile.in
linux-arm64-musl/Toolchain.cmake

This adds a `linux-arm64-musl` image, that leverages the toolchains available on [musl.cc](https://musl.cc).
I realized later that the existing linux-armv5-musl by @thewtex was using crosstool-ng instead, and I don't know what is best. @thewtex any opinion?

Add linux-arm64-musl image

---

.circleci/config.yml
Makefile
README.rst
linux-armv7l-musl/Dockerfile.in
linux-armv7l-musl/Toolchain.cmake

Adds support for the armv7l toolchain from musl.cc. Very similar to `linux-arm64-musl`.

Add linux-armv7l-musl image

---

.circleci/config.yml
Makefile
README.rst
linux-armv6-musl/Dockerfile.in
linux-armv6-musl/Toolchain.cmake

Following the addition of armv7l-musl and arm64-musl, here is armv6-musl :blush:. Also using the toolchain from musl.cc.

Add linux-armv6-musl image

---

common.windows

I propose to switch from gcc9.2, because I encounter runtime errors with recursive subroutine in fortran.
With version 10.2, these runtime errors have gone away

:sparkles: Switched to gcc10.2 for windows

---

Makefile
common.docker
imagefiles/install-python-packages.sh

cp35 is no longer supported and get-pip.py fails to build.

manylinux: Build pip with cp38

---

manylinux2014-x86/Dockerfile.in

Dear @thewtex,
this fixes your workaround from #377, but this time for the 32-bit `manylinux2014-x86` image. It will resolve #467.
With kind regards,
Andreas.
cc @figroc, @JonasVautherin, @zborowa

Fix "yum" on manylinux2014-x86

---

Makefile

Following the discussion in https://github.com/dockbuild/dockbuild/issues/69, I wanted to tag the base image like it is done for the other images, but I'm getting the following error (which I thought had been fixed recently :thinking:):
```
+ rm -f cmake-3.17.1-Centos5-x86_64.tar.gz
+ cd cmake-3.17.1-Centos5-x86_64
+ rm -rf doc man
+ rm -rf bin/cmake-gui
+ find . -type f -exec install -D '{}' '/usr/{}' ';'
+ command -v git
+ cd /usr/share
+ rm -rf liquidprompt
+ git clone https://github.com/nojhan/liquidprompt.git -b v_1.11
Cloning into 'liquidprompt'...
+ cat
+ chmod u+x /root/.bashrc
######################################################################## 100.0%
Hi there!
The URL you are using to fetch this script has changed, and this one will no
longer work. Please use get-pip.py from …
```

Tag base image like the others

---

common-manylinux.crosstool
common.crosstool
imagefiles/crosstool-ng-expat.patch
imagefiles/install-crosstool-ng-toolchain.sh

expat shall now be downloaded from github rather than sourceforge.
This commit patches crosstool-ng 1.23.0 to do this.
Pre-requisite to #482 
Fix #429

fix: crosstool-ng expat dowload

---

android-arm/Toolchain.cmake
android-arm64/Toolchain.cmake
android-x86/Toolchain.cmake
android-x86_64/Toolchain.cmake

`CMAKE_SYSTEM_PROCESSOR` is defined in the `android.toolchain.cmake` offered by Android NDK.
But it's not defined in `Toolchain.cmake`.

Define CMAKE_SYSTEM_PROCESSOR in Toolchain.cmake for Android build.

---

common.crosstool
imagefiles/install-crosstool-ng-toolchain.sh
linux-arm64/Dockerfile.in
linux-armv5/Dockerfile.in
linux-armv7/Dockerfile.in
linux-armv7a/Dockerfile.in
linux-mips/Dockerfile.in
linux-ppc64le/Dockerfile.in
linux-s390x/Dockerfile.in

It is now possible to choose the version of crosstool-ng per image, To make it easier to upgrade crosstool-ng to newer versions without having to update all images at the same time

Improve install-crosstool-ng-toolchain.sh script

---

.github/workflows/main.yml
Makefile

- Since docker 1.10, It is possible to put several tags during build
- Add purge rule in Makefile
- Fix tags that are not push, the last tags are two years ago (other than latest): https://hub.docker.com/r/dockcross/base/tags?page=1&ordering=last_updated

Improve Makefile

---

common.crosstool
linux-mips/Dockerfile.in
linux-mips/crosstool-ng.config

GCC 11
Linux 5.12.12
GLIBC 2.33
Binutils 2.36

Update linux-mips to latest crosstool-ng version

---

imagefiles/install-crosstool-ng-toolchain.sh
manylinux2014-aarch64/Dockerfile.in

Fix error on manylinux2014-aarch64
I tried with newer versions of crosstool-ng and GCC, but encountered many problems: https://github.com/dockcross/dockcross/issues/367

Fix error on manylinux2014-aarch64

---

common/common.windows

Update windows images to GCC 11.1 (From 10.x)
- Better support C++20 and C++17 by default
- Add support alderlake and znver3 (Ryzen 5xxx)
Source: https://gcc.gnu.org/gcc-11/changes.html

Update windows images to GCC 11.1

---

imagefiles/dockcross

implements the use of this solution using (recent) docker-desktop (implemented in wsl2), on windows host, from within cygwin environment.
(docker command line requires windows path, the conversion between cygwin path and windows path can be obtained via the cygwin specific cygpath instruction).

CYGWIN: introduce cygwin host system awareness.

---

.github/workflows/main.yml
Makefile
linux-armv6-lts/Dockerfile.in
linux-armv6-lts/Toolchain.cmake
linux-armv6-lts/crosstool-ng.config

Change compared to ARMv6 image (05-08-2021) :
- glibc 2.28
- min linux kernel to 4.19
- update linux header to 5.13
- update gcc to 11.2.0

Add linux-armv6 LTS version

---

windows-arm64/Dockerfile.in
windows-armv7/Dockerfile.in

Fixes newly introduced `llvm-mingw` builds as introduced in #557 
* Toolchain wrapper `llvm-mingw` doesn't provide a C preprocessor/precompiler (a.k.a. `CPP`), therefore it shouldn't be specified
* Removing `ENV CPP` allows `make` to fallback to `gcc -E`, which is normal behavior (this succeeds)
* `clang++` is technically valid, but is not an mingw-w64 "familiar" suffix, changed to `gcc`, `g++` for standardization (For example, if you unset all variables, the compiler will predict them as `gcc`, `g++`, not as `clang`, `clang++`)
See also: https://github.com/dockcross/dockcross/pull/557#pullrequestreview-727862804
**Warning/Note:** I'm not sure how to locally test this change.  (I know very little about Docker and my environment seems to be stuck on upstream at time of writing this)

Remove cpp, allow gcc -E fallback

---

imagefiles/build-and-install-openssl.sh

0b8587b72a5e9ce9aac7b3b086150051bb8276fa /  #574 downgraded openssl from 1.1.1k to 1.1.1i for some reason.

chore: bump openssl 1.1.1i → 1.1.1l

---

imagefiles/install-gosu-binary-wrapper.sh

Addresses:
/usr/local/bin/sudo: 5: 2: not found
that occurs during sudo execution.

imagefiles: gosu sudo wrapper requires bash

---

web-wasi/Dockerfile.in
web-wasi/Toolchain.cmake
web-wasi/wasmtime-pwd.sh

wasmtime is the official reference implementation and wasmer has
permission issues without sudo.

web-wasi: Use wasmtime instead of wasmer for the cross-compiling emulator

---

common/common.debian
common/common.windows
web-wasm/Dockerfile.in

Code-signing of generated executables is usually done with "signtool" on
Windows. When cross-compiling on Linux this tool is not available,
however, osslsigncode can be used as an replacement.
This patch simply apt-get installs osslsigncode to make it available inside the container.

add osslsigncode tool for Windows

---

web-wasi/Toolchain.cmake

This was changed in the web-wasm/web-wasi common tooling additions and
refactoring.

web-wasi: Update emulator path

---

common/common.docker
imagefiles/build-and-install-flatcc.sh

add flatcc to dockcross base image
Flatcc is a compiler that generates FlatBuffers code for C given a FlatBuffer schema file
see:
https://github.com/dvidelabs/flatcc
https://google.github.io/flatbuffers/
associated ticket: https://github.com/dockcross/dockcross/issues/668

add flatcc to Dockcross base image

---

imagefiles/dockcross.sh

This PR introduces 2 changes
* When looking for an `OCI_EXE`, check for podman first. Docker users usually only have docker installed. Podman users may link `docker` to `podman` as to not break scripts that have `docker` hard-coded. Alternative: Fail if both are found
* Don't set `USER_IDS` when using podman. Podman is most likely run in rootless mode. If it's not, it's going to be run with `sudo`. In neither of both cases, setting `USER_IDS` (as is done right now) is useful. This fixes #649. Alternative: Allow to manually set `USER_IDS`

Improve podman support

---

imagefiles/dockcross.sh

All images built for a linux/amd64 host.
Addresses warning when running an Apple M1:
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

dockcross-script: Specify --platform flag

---

android-arm/Dockerfile.in
android-arm64/Dockerfile.in
android-x86/Dockerfile
android-x86_64/Dockerfile

I always tend to forget, but there is no reason to keep the api to an old version, is there?
Also I renamed ANDROID_NDK_API to ANDROID_API because it seems to me that this is what it is.

Update android ndk to r25b and api to 33

---

android-arm/Dockerfile.in
android-arm64/Dockerfile.in
android-x86/Dockerfile
android-x86_64/Dockerfile

I finally found an answer to my question [here](https://developer.android.com/ndk/guides/common-problems#minsdkversion_set_higher_than_device_api_level):
> Problem: Your NDK API level is higher than the API supported by your device.
>
> Solution: Set your NDK API level (APP_PLATFORM) to the minimum version of Android your app supports.
So the API level, for NDK, is "the minimum version of Android the app supports". So it makes sense for dockcross to keep it low. API 23 is Android 6, which seems reasonable. That's also what it was before I updated the NDK a couple weeks ago.
Sorry about that, at least now I know how this number is meant to be used :innocent:!

Set Android ndk api back to 23 (Android 6.0)

---

Makefile
tools/dockcross-cmake-builder.sh
tools/dockcross-command.sh
tools/dockcross-make-builder.sh

This impacts the DEFAULT_DOCKCROSS_IMAGE in common.label-and-env which determines the default image version used by the dockcross script. We want the same tagged version of the image to be used its generated dockcross script (not `latest`).

Set VERSION build arg to image tag

---

common/common.debian

Netwide assembler is a small package, but when required it is hard to avoid it, e.g. https://github.com/google/tensorstore/issues/65#issuecomment-1324368082.
```log
$ apt show nasm
Package: nasm
Version: 2.15.05-1
Priority: optional
Section: universe/devel
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Anibal Monsalve Salazar <anibal@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 3,345 kB
Depends: dpkg (>= 1.15.4) | install-info, libc6 (>= 2.14) Homepage: http://www.nasm.us/
Download-Size: 375 kB
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages Description: General-purpose x86 assembler
Netwide Assembler.  NASM will currently output flat-form …
```

Add NASM package

---

README.md

You need the `-y` (aka `--assume-yes`) flag when running apt in a script otherwise the thing hangs forever waiting for interactive confirmation for some larger downloads.

Docs — Extending dockcross: run apt non-interactively

---

common/common.webassembly

- common.webassembly: Bump binaryen to 2022-12-17
- common.webassembly: Bump wabt to 1.0.32, 2022-12-27 main
- common.webassembly: Bump WAVM to 2022-05-14

wasm tools bump

---

web-wasi/Dockerfile.in
web-wasi/Toolchain.cmake
web-wasi/clang++-wasi-sysroot.sh
web-wasi/clang-wasi-sysroot.sh

The binary linux SDK in version 17 requires a newer glibc than we have
available, so we have to use our own patched clang. This follows the
approach in:
https://github.com/WebAssembly/wasi-sdk/pull/271

web-wasi: Bump to WASI-SDK 17

---

common/common.debian

These get installed via the openssh-server package, which is pulled in as a dependency. Remove them before completing the layer to avoid inadvertent usage in these public docker images.

base: Remove ssh keys

---

README.md
imagefiles/install-python-packages.sh

It was requested [here](https://github.com/dockcross/dockcross/issues/139), and I recently had a need for Meson. I tried it in my custom image by just adding `RUN sudo pip install meson` at the end of an image, but I figure this should work if it works with conan :nerd_face:.
Anyway I mostly want your opinion on that. Just meson needs to be installed and can then be used to (cross-)compile. We could provide default cross files (equivalent of the cmake toolchain files), but the user *must* explicitly call them with `--cross-file`, so it feels like a reasonable first step to just install Meson.
EDIT: I ran `make android-arm64` from scratch (locally), then verified that `meson --version` returns 1.0.0 in the image. So it seems to be working as far as I can tell :+1:

Add meson to all images

---

imagefiles/dockcross.sh

Ditto. 
With that specification in place, a locally built image on architectures != amd64 would fail to execute the `dockcross.sh` script and try to pull a non-existing amd64 image from docker.io repository under the custom organisation name.
That specification shall be anyway superfluous, unless one really wants to run an emulated image even if the native image is available.

Removed platform specification in dockcross.sh

---

manylinux2014-aarch64/crosstool-ng.config

This is the version used in the manylinux2014_aarch image documented at https://github.com/pypa/manylinux.

manylinux2014-aarch64: Bump to GCC 10

---

common/common.webassembly

**web-wasi** doesn't build on my computer and server (Manjaro and Debian 11), i updated [wabt](https://github.com/WebAssembly/wabt) to latest commit.
Current update ([1.0.32](https://github.com/WebAssembly/wabt/releases/tag/1.0.32)) doesn't not work for me :/
The commit that fixed the issue: https://github.com/WebAssembly/wabt/commit/5cb73ee2344c69e442ac6147ba7971992088f801
Build fail on **linux-arm64-full** isn't relate to this commit.
Logs (on 162287deb5aed774bdc66a220e877b5ea36e71c9 ) when i tried to build web-wasi
``` bash
make web-wasm
sed \
-e '/common.docker/ r common/common.docker' \
-e '/common.debian/ r common/common.debian' \
-e '/common.manylinux_2_28/ r common/common.manylinux_2_28' \
-e '/common.manylinux2014/ r common/common.manylinux2014' \
-e '/common.crosstool/ r …
```

Fix build failed with wabt on web-wasm image

---

web-wasm/Dockerfile.in

closes https://github.com/dockcross/dockcross/issues/776

web-wasm: Bump emscripten to 3.1.35

---

Makefile

This is simply setting some makefile variables as overridable so one can do:
```sh
make \
DOCKER=podman \
GEN_IMAGES=bare-m68k-newlib \
STANDARD_IMAGES=bare-m68k-newlib \
NON_STANDARD_IMAGES=""
```

makefile: use default variables, so one can add extra images

---

imagefiles/install-gosu-binary.sh

Fix architecture detection to match gosu's naming

install-gosu-binary: fix arch detection to match gosu releases

---

linux-riscv32/Dockerfile.in
linux-riscv64/Dockerfile.in

I believe a copy/paste error occurred while creating the RISCV32 and RISCV64 images where ARCH was set to `powerpc`.
Furthemore, I'm unsure if this is a typo:
https://github.com/dockcross/dockcross/blob/4282105d1189e7843dca3654d8ca5d4fea3fa6e8/linux-riscv32/Dockerfile.in#L42
Shouldn't this be:
```diff
- ENV PKG_CONFIG_PATH /usr/lib/riscv64-unknown-linux-gnu/pkgconfig 
+ ENV PKG_CONFIG_PATH /usr/lib/riscv32-unknown-linux-gnu/pkgconfig 
```
... or does the RISCV32 container actually use the RISCV64 pkgconfig prefix?

Fix RISCV typos

---

linux-armv5/Dockerfile.in

Allow `pkg-config` to find `.pc` files for the appropriate architecture.
* The `Makefile.in` for `linux-armv5` says the following:
>  This is for ARMv5 "legacy" (armel) devices **which do NOT support hard float VFP instructions (armhf)**
... however, the `PKG_CONFIG_PATH` points to a `hf` ("hard float") ABI: `arm-linux-gnueabihf`.  I believe this is a typo.
* The `PKG_CONFIG_PATH` points to the root of `/usr/lib/arm-linux-gnueabihf/`.  I believe this is a second typo.
... assuming the intention is to point to a subdirectory which contains `.pc` files, this would be `/usr/lib/arm-linux-gnueabihf/pkgconfig` (or in this case, `/usr/lib/arm-linux-gnueabi/pkgconfig/`).  Example `.pc` file: https://packages.debian.org/bullseye/armel/libhidapi-dev/filelist
Partially related, I believe this …

Fix linux-armv5 typo

---

CONTRIBUTING.md
README.md

Spelling fixes in the markdown files.
```
ou -> you
evan -> even
```

spelling fixes in docs

---

.github/workflows/main.yml
Makefile

Enabling build the dockcross images with `podman`.
Enable building multiple architecture images for both amd64 and arm64. arm64 hosts, e.g. an Apple Silicon mac, can run the amd64, but the emulation is quite slow.

Enable specification of build tool with OCI_EXE, building images for arm64 hosts

---

linux-armv7a/Dockerfile.in
linux-armv7a/crosstool-ng.config

Updates crosstool, gcc and kernel headers

linux-armv7a: bump gcc to 12.3.0 and kernel headers to 6.1.35

---

.github/workflows/main.yml
Makefile
linux-m68k-uclibc/Dockerfile.in
linux-ppc64le-lts/Dockerfile.in
linux-ppc64le/Dockerfile.in
linux-riscv32/Dockerfile.in
linux-riscv64/Dockerfile.in
linux-xtensa-uclibc/Dockerfile.in
manylinux2014-x64/Dockerfile.in
manylinux2014-x86/Dockerfile.in
manylinux_2_28-x64/Dockerfile.in

It seems that wiki.qemu-project.org is not available anymore and downloads are now on download.qemu.org.
This is something I noticed when doing a full local build in preparation to work on #838.

Correct the qemu download URLs

---

common/common.windows

The upgrade cmake to 3.29.6, closes #838.
I also upgraded cmake in all other images so the versions are aligned

Upgrade MXE to todays latest commit

---

common/common.debian

This PR adds ccache to the debian based containers.
It should work as expected but some testing is probably required.
Resolves #845.

add ccache to common debian container

---

test/run.py
web-wasm/Dockerfile.in

- web-wasm: bump emscripten to 3.1.64
- test: bump cmake_minimum_required to 3.16

emscripten 3 1 64

---

imagefiles/wasmtime-pwd-threads.sh

In recent wasmtime, `-S` flags need to come after `run`.
Also add `-W threads=y` following the wasmtime test suite,
- https://github.com/bytecodealliance/wasmtime/blob/fc3c868b13bccf5d7ed26de4cfd1a2dc4c689360/tests/all/cli_tests.rs#L580-L581
Also explicity enable the `cli` feature because this is used for CMake
try_run.

wasi: fix threads option specification for wasmtime

---

.github/workflows/main.yml

Make CI more reproducible and prevent non-explicit changes from breaking
builds.

ci: use versioned build image

---

README.md
android-arm/Dockerfile.in
android-arm/config.toml
android-arm64/Dockerfile.in
android-arm64/config.toml
android-x86/Dockerfile
android-x86/config.toml
android-x86_64/Dockerfile
android-x86_64/config.toml
common/common.docker
imagefiles/build-and-install-rustup.sh

I have been using it with android-arm64 and it works for me :tada:.
I haven't tested the other images on a real device, but they seem to build my project fine, as shown in the output of `file`:
```
% file target/aarch64-linux-android/debug/libmyproject.so
target/aarch64-linux-android/debug/libmyproject.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, for Android 23, built by NDK r25b (8937393), with debug_info, not stripped
% file target/armv7-linux-androideabi/debug/libmyproject.so
target/armv7-linux-androideabi/debug/libmyproject.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, for Android 23, built by NDK r25b (8937393), with debug_info, not stripped
% file target/i686-linux-android/debug/libmyproject.so …
```

Install rustup globally and add Rust support to Android images

---

.github/workflows/main.yml

Use the directory similar to `base`.

ci: fix multiarch deploy path

---

linux-arm64-musl/Dockerfile.in
linux-arm64-musl/config.toml

Hello, I've added support of building rust binaries with `linux-arm64-musl` image. Similarly as it added to android images in  https://github.com/dockcross/dockcross/pull/867. Also it have pre-installed [cbindgen](https://github.com/mozilla/cbindgen), because it frequently used  in  multi-language projects.

Add Rust support to linux-arm64-musl

---

imagefiles/build-and-install-openssl.sh

Following the latest update of perl (by @bensuperpc [here](https://github.com/dockcross/dockcross/pull/865)), my building images with podman fails with tons of tar errors like this ones:
```
[...]
tar: perl-5.40.1/dist/if/Makefile.PL: Cannot change ownership to uid 197609, gid 197609: Invalid argument
tar: perl-5.40.1/dist/if/MANIFEST: Cannot change ownership to uid 197609, gid 197609: Invalid argument
tar: perl-5.40.1/dist/if/META.json: Cannot change ownership to uid 197609, gid 197609: Invalid argument
tar: perl-5.40.1/dist/if/META.yml: Cannot change ownership to uid 197609, gid 197609: Invalid argument
[...]
```
I seems like the same problem has been encountered a few years ago (not for perl, though) and solved in https://github.com/dockcross/dockcross/pull/396.
Doing the same thing …

Untar perl with --no-same-owner

---

common/common.windows

The cross root variable is useful when there is need to install additional libs in a child dockerfile, so ensure it is set in the windows variants.

Add CROSS_ROOT env variable on windows

---

Makefile

For:
```
Makefile:297: target '-e' given more than once in the same rule
35
Makefile:305: warning: overriding recipe for target 'base-shell'
36
Makefile:298: warning: ignoring old recipe for target 'base-shell'
37
Makefile:305: warning: overriding recipe for target 'uname'
38
Makefile:298: warning: ignoring old recipe for target 'uname'
39
Makefile:305: warning: overriding recipe for target '-m'
40
Makefile:298: warning: ignoring old recipe for target '-m'
41
Makefile:305: warning: overriding recipe for target '|'
42
Makefile:298: warning: ignoring old recipe for target '|'
43
Makefile:305: warning: overriding recipe for target 'sed'
44
Makefile:298: warning: ignoring old recipe for target 'sed'
45
Makefile:305: warning: overriding recipe for target '-e'
46
Makefile:298: warning: ignoring …
```

Makefile: address HOST_ARCH specification syntax

---

imagefiles/entrypoint.sh

Partially fixes #886, see details there.
--
Presumably we do not need those as root.
This slows down the container startup for what appears to be no
good reason.
This workaround was added in 2016:
dd9d902538b350a7388525e786db99be10b4f6a5 ,
see also https://github.com/moby/moby/issues/13594#issuecomment-262441366 ,
and hopefully AUFS has been fixed by now.

Speed up dockcross entrypoint

---

imagefiles/entrypoint.sh

Seeing a bunch of these in CI, where `/dev/pts/0` does not exist:
```
chown: cannot access '/dev/pts/0': No such file or directory
```
Fixes #891, @maxiaogood FYI.

entrypoint.sh: Silence errors if /dev/pts/0 does not exist

---

imagefiles/entrypoint.sh

Only move `/root/.rustup` and `/root/.cargo` directories if they exist. This prevents errors when re-using the script in environments where Rust is not installed (e.g. https://github.com/dockbuild/dockbuild).
Previously, `mv` would fail if either directory was missing:
```
mv: cannot stat '/root/.rustup': No such file or directory
mv: cannot stat '/root/.cargo': No such file or directory
```

fix(entrypoint.sh): Avoid error if rustup is not installed

---

imagefiles/install-gosu-binary.sh

The preferred server matches the official documentation. See https://github.com/tianon/gosu/blob/master/INSTALL.md
It was introduced upstream through https://github.com/tianon/gosu/commit/169711453c89322c6052c1c2eb6865818caae01b

fix(install-gosu-binary): Prefer checking key from server using "hkps" protocol
